---
title: Optimize CPU/Processor Settings
description: Optimizes CPU scheduling and power management for maximum performance
actions:
  # Set power plan to High Performance
  - !run: {exe: 'powercfg', args: '/setactive 8c5e7fda-e8bf-45a6-a6cc-4b3c6af00375'}

  # Enable C-State coordination
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Power'
    value: 'CsEnabled'
    data: '0'
    type: REG_DWORD

  # Disable processor parking
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583'
    value: 'ACSettingIndex'
    data: '0'
    type: REG_DWORD
    ignoreErrors: true
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583'
    value: 'DCSettingIndex'
    data: '0'
    type: REG_DWORD
    ignoreErrors: true

  # Disable processor idle state
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\5d76a2ca-e8c0-402f-a133-2158492d58ad'
    value: 'ACSettingIndex'
    data: '0'
    type: REG_DWORD
    ignoreErrors: true
