---
title: Respect Power Modes Windows Search Indexing
description: Respects current power mode for indexing to prevent battery drainage
actions:
    - !registryValue: {value: 'RespectPowerModes', data: 1, type: REG_DWORD}