---
title: Set File Associations
description: Sets file associations for the user-selected web browser and other apps
actions:
  - !run:
    exe: 'FILEASSOC.cmd'
    exeDir: true
    option: '!uninstall-edge'
  - !run:
    exe: 'FILEASSOC.cmd'
    args: '"Firefox"'
    option: 'install-another-browser'
    exeDir: true
