---
title: Disable Use Check Boxes to Select Items
description: Disables check boxes in File Explorer to select items for QoL
actions:
    - !registryValue: {value: 'AutoCheckSelect', data: 0, type: REG_DWORD}