---
title: Don't Show Office Files
description: Don't show Office files in Quick Access (Home)
builds: [ '>=22000' ]
actions:
    - !registryValue: {value: 'ShowCloudFilesInQuickAccess', data: 0, type: REG_DWORD}