---
title: Remove Shortcut Text
description: Removes '- Shortcut' text appended onto the end of shortcuts for QoL
actions:
    - !registryValue: {value: 'ShortcutNameTemplate', data: '', type: REG_SZ}