---
title: Disable Performance Track
description: Disables tracking of responsiveness events for privacy
actions:
    # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.PerformancePerftrack::WdiScenarioExecutionPolicy
    - !registryValue: {value: 'ScenarioExecutionEnabled', data: 0, type: REG_DWORD}