---
title: Disable Resultant Set of Policy (RSoP) Logging
description: Disables logging of Group Policy settings (RSoP) for privacy
actions:
    - !registryValue: {value: 'RSoPLogging', data: 0, type: REG_DWORD}