---
title: Disable Tips
description: Disables tips for QoL and privacy
actions:
  # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.CloudContent::DisableSoftLanding
    - !registryValue: {value: 'DisableSoftLanding', data: 1, type: REG_DWORD}