---
title: Disable NVIDIA Control Panel Telemetry
description: Disables NVIDIA Control Panel telemetry for privacy
actions:
    - !registryValue: {value: 'OptInOrOutPreference', data: 0, type: REG_DWORD}