---
title: Show Command Prompt on Win+X
description: Shows Command Prompt instead of PowerShell on Windows + X, as it is what most users are familar with
actions:
    - !registryValue: {value: 'DontUsePowerShellOnWinX', data: 1, type: REG_DWORD}